# Generated by Django 5.1 on 2024-08-12 20:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Pizza',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=50)),
                ('ingredientes', models.CharField(max_length=200)),
                ('imagem', models.ImageField(blank=True, null=True, upload_to='pizzas/')),
                ('data_alteracao', models.DateTimeField(auto_now=True)),
                ('pizza_ativa', models.BooleanField(blank=True, default=1, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Review',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.IntegerField()),
                ('pizza', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='core.pizza')),
            ],
        ),
    ]
