# Generated by Django 5.1 on 2024-08-13 11:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_pizza_descricao_alter_pizza_data_alteracao_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='review',
            old_name='rating',
            new_name='avaliacao',
        ),
    ]
