# Generated by Django 5.1 on 2024-08-13 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_rename_rating_review_avaliacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Review',
            new_name='Avaliacao',
        ),
    ]
