# Generated by Django 5.1 on 2024-08-13 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_rename_review_avaliacao'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Avaliacao',
            new_name='Feedback',
        ),
    ]
